Repository GodotVR/godot-xr-tools, pull requests merged in 2022-11, with the labels that each got.

#244 Improve transparency settings and add unshaded settings
  addons/godot-xr-tools/objects/viewport_2d_in_3d.gd
  scenes/pointer_demo/pointer_demo.tscn
Labels: enhancement

#249 [CI] Move LICENSE, CONTRIBUTORS.md and VERSIONS.md
  .github/workflows/build-on-push.yml
Labels: enhancement, build-ci

#231 Implement method of exchanging base hand animations
  .gitignore
  VERSIONS.md
  addons/godot-xr-tools/assets/hand_blend_tree.tres
  addons/godot-xr-tools/assets/hands/left_hand.blend1
  addons/godot-xr-tools/assets/left_hand.blend
  addons/godot-xr-tools/assets/left_hand.glb
  addons/godot-xr-tools/assets/left_hand.glb.import
  addons/godot-xr-tools/assets/left_hand.tscn
  addons/godot-xr-tools/assets/left_physics_hand.tscn
  addons/godot-xr-tools/assets/right_hand.glb
  addons/godot-xr-tools/assets/right_hand.glb.import
  addons/godot-xr-tools/assets/right_hand.tscn
  addons/godot-xr-tools/assets/right_physics_hand.tscn
  addons/godot-xr-tools/functions/movement_provider.gd
  addons/godot-xr-tools/hands/hand.gd
  addons/godot-xr-tools/hands/hand_blend_tree.tres
  addons/godot-xr-tools/hands/hand_physics_bone.gd
  addons/godot-xr-tools/hands/left_hand.tscn
  addons/godot-xr-tools/hands/left_hand_low.tscn
  addons/godot-xr-tools/hands/left_physics_hand.tscn
  addons/godot-xr-tools/hands/left_physics_hand_low.tscn
  addons/godot-xr-tools/hands/physics_hand.gd
  addons/godot-xr-tools/hands/right_hand.tscn
  addons/godot-xr-tools/hands/right_hand_low.tscn
  addons/godot-xr-tools/hands/right_physics_hand.tscn
  addons/godot-xr-tools/hands/right_physics_hand_low.tscn
  addons/godot-xr-tools/player/player_body.gd
  addons/godot-xr-tools/player/player_body.tscn
  addons/godot-xr-tools/player/poke/poke.gd
  addons/godot-xr-tools/player/poke/poke.tscn
  addons/godot-xr-tools/player/poke/poke_body.gd
  project.godot
  scenes/basic_movement_demo/basic_movement_demo.tscn
  scenes/climbing_gliding_demo/climbing_gliding_demo.tscn
  scenes/grappling_demo/grappling_demo.tscn
  scenes/interactables_demo/interactables_demo.tscn
  scenes/main_menu/main_menu_level.tscn
  scenes/pickable_demo/pickable_demo.tscn
  scenes/pointer_demo/pointer_demo.tscn
  scenes/poke_demo/poke_demo.tscn
  scenes/teleport_demo/teleport_demo.tscn
Labels: enhancement

#273 Added hand-pose area support
  addons/godot-xr-tools/functions/function_pose_detector.gd
  addons/godot-xr-tools/functions/function_pose_detector.tscn
  addons/godot-xr-tools/hands/animations/left/Sign_Point.anim
  addons/godot-xr-tools/hands/animations/right/Sign_Point.anim
  addons/godot-xr-tools/hands/hand.gd
  addons/godot-xr-tools/hands/poses/hand_pose_settings.gd
  addons/godot-xr-tools/hands/poses/pose_default_left.tres
  addons/godot-xr-tools/hands/poses/pose_default_right.tres
  addons/godot-xr-tools/hands/poses/pose_point_left.tres
  addons/godot-xr-tools/hands/poses/pose_point_right.tres
  addons/godot-xr-tools/hands/scenes/highpoly/left_fullglove_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/left_fullglove_physics_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/left_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/left_physics_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/right_fullglove_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/right_fullglove_physics_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/right_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/right_physics_hand.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/left_fullglove_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/left_hand_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/left_physics_fullglove_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/left_physics_hand_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/right_fullglove_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/right_hand_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/right_physics_fullglove_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/right_physics_hand_low.tscn
  addons/godot-xr-tools/objects/hand_pose_area.gd
  addons/godot-xr-tools/objects/hand_pose_area.tscn
  assets/meshes/interactables/joystick_smooth.tscn
  assets/meshes/interactables/joystick_snap.tscn
  assets/meshes/interactables/joystick_zero.tscn
  assets/meshes/interactables/lever_smooth.tscn
  assets/meshes/interactables/lever_snap.tscn
  assets/meshes/interactables/lever_zero.tscn
  assets/meshes/interactables/pose_grab_ball_left.tres
  assets/meshes/interactables/pose_grab_ball_right.tres
  assets/meshes/interactables/pose_grab_wheel_left.tres
  assets/meshes/interactables/pose_grab_wheel_right.tres
  assets/meshes/interactables/push_button.tscn
  assets/meshes/interactables/slider_smooth.tscn
  assets/meshes/interactables/slider_snap.tscn
  assets/meshes/interactables/slider_zero.tscn
  assets/meshes/interactables/wheel_smooth.tscn
  project.godot
  scenes/interactables_demo/interactables_demo.tscn
  scenes/main_menu/main_menu_level.tscn
  scenes/main_menu/objects/settings_ui.tscn
  scenes/poke_demo/poke_demo.tscn
Labels: enhancement

#275 Fix interactible area button emit_signal
  addons/godot-xr-tools/interactables/interactable_area_button.gd
Labels: bug

#287 update ghost_hand.material to be in xr tools hand folder
  addons/godot-xr-tools/hands/materials/ghost_hand.tres
  addons/godot-xr-tools/hands/materials/glove_caucasian_dark_camo.material
  scenes/climbing_gliding_demo/climbing_gliding_demo.tscn
  scenes/sprinting_demo/sprinting_demo.tscn
Labels: enhancement

#286 Implement solution to use stored blend trees
  addons/godot-xr-tools/hands/hand.gd
  addons/godot-xr-tools/hands/scenes/highpoly/left_fullglove_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/left_fullglove_physics_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/left_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/left_physics_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/left_physics_tac_glove.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/left_tac_glove.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/right_fullglove_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/right_fullglove_physics_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/right_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/right_physics_hand.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/right_physics_tac_glove.tscn
  addons/godot-xr-tools/hands/scenes/highpoly/right_tac_glove.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/left_fullglove_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/left_hand_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/left_physics_fullglove_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/left_physics_hand_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/left_physics_tac_glove_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/left_tac_glove_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/right_fullglove_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/right_hand_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/right_physics_fullglove_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/right_physics_hand_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/right_physics_tac_glove_low.tscn
  addons/godot-xr-tools/hands/scenes/lowpoly/right_tac_glove_low.tscn
Labels: bug
