Repository GodotVR/godot-xr-tools, pull requests merged in 2022-12, with the labels that each got.

#292 add option to rotate player on arms roll movement, during glide action
  addons/godot-xr-tools/functions/movement_glide.gd
  scenes/climbing_gliding_demo/climbing_gliding_demo.tscn
Labels: enhancement

#293 Make new XROrigin3D current after loading new scene
  addons/godot-xr-tools/staging/scene_base.gd
  addons/godot-xr-tools/staging/staging.gd
Labels: port to Godot 4

#310 Clean godot-xr-tools to have no warnings against gdlint
  .github/workflows/gdlint-on-push.yml
  addons/godot-xr-tools/assets/resource_queue/resource_queue.gd
  addons/godot-xr-tools/effects/vignette.gd
  addons/godot-xr-tools/functions/function_pickup.gd
  addons/godot-xr-tools/functions/function_teleport.gd
  addons/godot-xr-tools/functions/movement_direct.gd
  addons/godot-xr-tools/functions/movement_flight.gd
  addons/godot-xr-tools/functions/movement_glide.gd
  addons/godot-xr-tools/functions/movement_grapple.gd
  addons/godot-xr-tools/functions/movement_physical_jump.gd
  addons/godot-xr-tools/functions/movement_provider.gd
  addons/godot-xr-tools/functions/movement_sprint.gd
  addons/godot-xr-tools/hands/hand.gd
  addons/godot-xr-tools/interactables/interactable_area_button.gd
  addons/godot-xr-tools/interactables/interactable_hinge.gd
  addons/godot-xr-tools/interactables/interactable_joystick.gd
  addons/godot-xr-tools/misc/arvr_helpers.gd
  addons/godot-xr-tools/objects/grab_points/grab_point_hand.gd
  addons/godot-xr-tools/objects/pickable.gd
  addons/godot-xr-tools/objects/viewport_2d_in_3d.gd
  addons/godot-xr-tools/overrides/ground_physics.gd
  addons/godot-xr-tools/overrides/ground_physics_settings.gd
  addons/godot-xr-tools/player/player_body.gd
  addons/godot-xr-tools/plugin.gd
  addons/godot-xr-tools/staging/loading_screen.gd
  addons/godot-xr-tools/staging/staging.gd
  project.godot
  scenes/pointer_demo/pointer_demo.gd
Labels: enhancement

#309 Implement threaded loading of scenes.
  addons/godot-xr-tools/staging/staging.gd
Labels: bug
