Repository GodotVR/godot-xr-tools, pull requests merged in 2023-11, with the labels that each got.

#551 Fix grappling on gridmaps
  VERSIONS.md
  addons/godot-xr-tools/functions/movement_grapple.gd
Labels: enhancement

#520 Add world-grab movement support
  VERSIONS.md
  addons/godot-xr-tools/functions/movement_world_grab.gd
  addons/godot-xr-tools/functions/movement_world_grab.tscn
  addons/godot-xr-tools/objects/world_grab_area.gd
  addons/godot-xr-tools/objects/world_grab_area.tscn
  scenes/main_menu/main_menu_level.tscn
  scenes/teleport_demo/teleport_demo.tscn
  scenes/world_grab_demo/objects/arena_block.tscn
  scenes/world_grab_demo/objects/arena_cylinder.tscn
  scenes/world_grab_demo/objects/arena_floor.tscn
  scenes/world_grab_demo/objects/arena_wall.tscn
  scenes/world_grab_demo/world_grab_demo.png
  scenes/world_grab_demo/world_grab_demo.png.import
  scenes/world_grab_demo/world_grab_demo.tscn
Labels: enhancement, needstesting

#575 Add grab-points to climbing
  VERSIONS.md
  addons/godot-xr-tools/objects/climbable.gd
  scenes/climbing_gliding_demo/climbing_gliding_demo.tscn
  scenes/climbing_gliding_demo/objects/ladder.tscn
Labels: enhancement

#573 Control physical keyboard and gamepad inputs for Viewport2Din3D
  VERSIONS.md
  addons/godot-xr-tools/objects/viewport_2d_in_3d.gd
Labels: enhancement

#571 Upgrade use of legacy properties in the Viewport2Din3D script
  addons/godot-xr-tools/objects/viewport_2d_in_3d.gd
Labels: bug

#576 Prepare release 4.3.0
  addons/godot-xr-tools/hands/blend/animations/animations_hand_l.blend.import
  addons/godot-xr-tools/hands/blend/animations/animations_hand_r.blend.import
  addons/godot-xr-tools/hands/blend/hand_l.blend.import
  addons/godot-xr-tools/hands/blend/hand_r.blend.import
  addons/godot-xr-tools/materials/highlight.tres
  addons/godot-xr-tools/misc/hold_button_visualshader.tres
  addons/godot-xr-tools/plugin.cfg
  addons/godot-xr-tools/staging/loading_screen/loading_screen_shader.tres
  assets/meshes/knife/knife.blend.import
  assets/meshes/mound/mound.blend.import
  assets/meshes/ramps/ramps.blend.import
  assets/meshes/teacup/teacup.blend.import
  assets/meshes/teleport/teleport.blend.import
  assets/meshes/tube/tube.blend.import
Labels: enhancement
