Repository GodotVR/godot-xr-tools, pull requests merged in 2023-01, with the labels that each got.

#301 Add support for WebXR
  addons/godot-xr-tools/objects/viewport_2d_in_3d.tscn
  addons/godot-xr-tools/plugin.gd
  addons/godot-xr-tools/staging/scene_base.gd
  addons/godot-xr-tools/user_settings/user_settings.gd
  addons/godot-xr-tools/user_settings/user_settings_ui.gd
  addons/godot-xr-tools/user_settings/user_settings_ui.tscn
  addons/godot-xr-tools/webxr/enter_webxr_ui.gd
  addons/godot-xr-tools/webxr/enter_webxr_ui.tscn
  export_presets.cfg
  scenes/basic_movement_demo/basic_movement_demo.tscn
  scenes/climbing_gliding_demo/climbing_gliding_demo.tscn
  scenes/grappling_demo/grappling_demo.tscn
  scenes/interactables_demo/interactables_demo.tscn
  scenes/main_menu/main_menu_level.gd
  scenes/main_menu/main_menu_level.tscn
  scenes/pickable_demo/pickable_demo.tscn
  scenes/pointer_demo/pointer_demo.gd
  scenes/pointer_demo/pointer_demo.tscn
  scenes/poke_demo/poke_demo.tscn
  scenes/scene_base.gd
  scenes/sprinting_demo/sprinting_demo.tscn
  scenes/teleport_demo/teleport_demo.tscn
  staging.tscn
Labels: enhancement

#312 Added initial WebXR entry UI and export target.
  addons/godot-xr-tools/staging/loading_screen.gd
  addons/godot-xr-tools/staging/staging.gd
  addons/godot-xr-tools/staging/staging.tscn
  addons/godot-xr-tools/xr/start_xr.gd
  addons/godot-xr-tools/xr/start_xr.tscn
  export_presets.cfg
  project.godot
  staging.gd
  staging.tscn
Labels: enhancement

#314 Merged StartXR functionality from master branch.
  addons/godot-xr-tools/staging/scene_base.tscn
  addons/godot-xr-tools/staging/staging.gd
  addons/godot-xr-tools/staging/staging.tscn
  addons/godot-xr-tools/webxr/enter_webxr_ui.gd
  addons/godot-xr-tools/webxr/enter_webxr_ui.tscn
  addons/godot-xr-tools/xr/start_xr.gd
  addons/godot-xr-tools/xr/start_xr.tscn
  project.godot
  staging.gd
  staging.tscn
  start_xr.gd
Labels: enhancement

#324 Added render_target_size_multiplier property to StartXR node.
  addons/godot-xr-tools/xr/start_xr.gd
Labels: enhancement

#322 Flapping wings. Add vertical impulse when flapping arms
  CONTRIBUTORS.md
  addons/godot-xr-tools/functions/movement_glide.gd
  scenes/climbing_gliding_demo/climbing_gliding_demo.tscn
  scenes/climbing_gliding_demo/objects/instructions.tscn
  scenes/climbing_gliding_demo/objects/instructions_2d.tscn
  scenes/climbing_gliding_demo/objects/ring.tscn
Labels: enhancement

#321 Make Demos show fancier
  assets/meshes/teleport/teleport.gd
  scenes/main_menu/main_menu_level.gd
Labels: enhancement

#332 Formatting cleanups and merges from the 4.0-dev branch.
  VERSIONS.md
  addons/godot-xr-tools/functions/movement_glide.gd
  addons/godot-xr-tools/functions/movement_turn.gd
  addons/godot-xr-tools/objects/grab_points/grab_point_hand.gd
  addons/godot-xr-tools/player/player_body.gd
  assets/meshes/teleport/teleport.gd
  demo_staging.gd
  demo_staging.tscn
  project.godot
  scenes/main_menu/main_menu_level.gd
  scenes/main_menu/main_menu_level.tscn
  scenes/pickable_demo/objects/snap_tray.tscn
  scenes/pickable_demo/objects/teacup.tscn
  scenes/sprinting_demo/sprinting_demo.png.import
Labels: cleanup

#330 Single swapping function pointer3
  addons/godot-xr-tools/functions/function_pointer.gd
  scenes/pointer_demo/pointer_demo.gd
  scenes/pointer_demo/pointer_demo.tscn
Labels: enhancement

#340 Update README.md (spelling)
  README.md
Labels: bug

#343 Rename access methods for Godot 4 Beta 15 and onwards
  addons/godot-xr-tools/functions/function_pickup.gd
  addons/godot-xr-tools/functions/function_teleport.gd
  addons/godot-xr-tools/functions/movement_direct.gd
  addons/godot-xr-tools/functions/movement_flight.gd
  addons/godot-xr-tools/functions/movement_turn.gd
  addons/godot-xr-tools/hands/hand.gd
Labels: breaking, port to Godot 4
