Repository GodotVR/godot-xr-tools, pull requests merged in 2023-08, with the labels that each got.

#492 Mark project settings as basic so they are always shown
  addons/godot-xr-tools/plugin.gd
Labels: bug

#493 Viewport 2D in 3D material cleanups
  VERSIONS.md
  addons/godot-xr-tools/objects/viewport_2d_in_3d.gd
Labels: enhancement

#497 Handle scaling of Viewport2Din3D
  addons/godot-xr-tools/objects/viewport_2d_in_3d.tscn
  addons/godot-xr-tools/objects/viewport_2d_in_3d_body.gd
Labels: enhancement

#506 Added check for a valid `AudioStreamPlayer3D` node.
  addons/godot-xr-tools/objects/snap_zone.gd
Labels: bug

#504 Teleport improvements
  VERSIONS.md
  addons/godot-xr-tools/functions/function_teleport.gd
  addons/godot-xr-tools/functions/function_teleport.tscn
Labels: enhancement

#503 Improve control over pickable object highlighting
  VERSIONS.md
  addons/godot-xr-tools/functions/function_pickup.gd
  addons/godot-xr-tools/objects/climbable.gd
  addons/godot-xr-tools/objects/pickable.gd
  addons/godot-xr-tools/objects/snap_zone.gd
Labels: enhancement

#496 Add world scaling to demos
  VERSIONS.md
  addons/godot-xr-tools/functions/function_pointer.gd
  addons/godot-xr-tools/functions/function_pointer.tscn
  addons/godot-xr-tools/objects/viewport_2d_in_3d.gd
  addons/godot-xr-tools/objects/viewport_2d_in_3d.tscn
  addons/godot-xr-tools/player/player_body.gd
  addons/godot-xr-tools/player/poke/poke.gd
  addons/godot-xr-tools/player/poke/poke.tscn
  addons/godot-xr-tools/plugin.gd
  assets/meshes/control_pad/control_pad.gd
  assets/meshes/control_pad/control_pad.tscn
  assets/meshes/control_pad/control_pad_display.gd
  assets/meshes/control_pad/control_pad_display.tscn
  assets/meshes/control_pad/control_pad_location.gd
  assets/meshes/control_pad/control_pad_location_left.tscn
  assets/meshes/control_pad/control_pad_location_right.tscn
  demo_staging.gd
  project.godot
  scenes/audio_demo/audio_demo.tscn
  scenes/basic_movement_demo/basic_movement_demo.tscn
  scenes/climbing_gliding_demo/climbing_gliding_demo.tscn
  scenes/grappling_demo/grappling_demo.tscn
  scenes/interactables_demo/interactables_demo.tscn
  scenes/main_menu/main_menu_level.tscn
  scenes/origin_gravity_demo/origin_gravity_demo.tscn
  scenes/pickable_demo/pickable_demo.tscn
  scenes/pointer_demo/pointer_demo.tscn
  scenes/poke_demo/poke_demo.tscn
  scenes/sphere_world_demo/sphere_world_demo.tscn
  scenes/sprinting_demo/sprinting_demo.tscn
  scenes/teleport_demo/teleport_demo.tscn
Labels: enhancement

#508 Cleanup teleport
  VERSIONS.md
  addons/godot-xr-tools/functions/function_teleport.gd
  addons/godot-xr-tools/materials/teleport.gdshader
  addons/godot-xr-tools/materials/teleport.tres
  addons/godot-xr-tools/objects/teleport_area.gd
  addons/godot-xr-tools/objects/teleport_area.tscn
  addons/godot-xr-tools/player/player_body.gd
  scenes/teleport_demo/objects/teleport_area_end.tscn
  scenes/teleport_demo/objects/teleport_area_metal.tres
  scenes/teleport_demo/objects/teleport_area_start.tscn
  scenes/teleport_demo/objects/teleport_end.tres
  scenes/teleport_demo/objects/teleport_start.tres
  scenes/teleport_demo/teleport_demo.tscn
Labels: enhancement

#507 Added multi-touch support
  VERSIONS.md
  addons/godot-xr-tools/events/pointer_event.gd
  addons/godot-xr-tools/functions/function_pointer.gd
  addons/godot-xr-tools/functions/function_pointer.tscn
  addons/godot-xr-tools/objects/interactable_area.gd
  addons/godot-xr-tools/objects/interactable_body.gd
  addons/godot-xr-tools/objects/keyboard/virtual_key.gd
  addons/godot-xr-tools/objects/keyboard/virtual_key.tscn
  addons/godot-xr-tools/objects/keyboard/virtual_key_char.gd
  addons/godot-xr-tools/objects/keyboard/virtual_keyboard_2d.gd
  addons/godot-xr-tools/objects/keyboard/virtual_keyboard_2d.tscn
  addons/godot-xr-tools/objects/viewport_2d_in_3d.gd
  addons/godot-xr-tools/objects/viewport_2d_in_3d.tscn
  addons/godot-xr-tools/objects/viewport_2d_in_3d_body.gd
  addons/godot-xr-tools/objects/virtual_keyboard.tscn
  addons/godot-xr-tools/player/poke/poke.gd
  scenes/main_menu/objects/settings_ui.tscn
  scenes/pickable_demo/objects/snap_tray.gd
  scenes/pointer_demo/objects/color_change_cube.gd
  scenes/pointer_demo/objects/color_change_cube.tscn
  scenes/pointer_demo/objects/pointer_laser_hit_material.tres
  scenes/pointer_demo/objects/pointer_laser_material.tres
  scenes/pointer_demo/objects/pointer_target_material.tres
  scenes/pointer_demo/pointer_demo.tscn
Labels: enhancement

#512 Add missing pages from the old WIKI
  _data/docs.yml
  _docs/index.md
  _docs/installation.md
  _docs/interaction/pointer.md
  _docs/player/physics_resource.md
  _docs/player/vignette.md
  _docs/setup.md
  _docs/staging/staging.md
  assets/img/arvr_setup.png
  assets/img/player_body/vignette_view.png
  assets/img/player_body/xr_vignette.png
  assets/img/pointer/xr_2d_ui.png
  assets/img/pointer/xr_pointer_function.png
  assets/img/pointer/xr_viewport2din3d.png
  assets/img/project_settings_plugin.png
  assets/img/xr_setup.png
  assets/img/xr_shader_cache.png
Labels: enhancement, documentation
