Repository GodotVR/godot-xr-tools, pull requests merged in 2023-10, with the labels that each got.

#539 Upgrade to Godot 4.1
  README.md
  VERSIONS.md
  project.godot
Labels: enhancement

#543 Fix hand pose on held object destruction
  addons/godot-xr-tools/objects/pickable.gd
Labels: bug

#531 Updated README.md with link to custom hand poses tutorial
  README.md
Labels: documentation

#515 Fix issues with static body not being detected by area3D
  addons/godot-xr-tools/hands/scenes/collision/collision_hand_left.tscn
  addons/godot-xr-tools/hands/scenes/collision/collision_hand_right.tscn
  addons/godot-xr-tools/objects/force_body/force_body.gd
  addons/godot-xr-tools/player/poke/poke.tscn
Labels: bug

#532 enable OptionButton to work from vr-simulator
  addons/godot-xr-tools/objects/viewport_2d_in_3d.gd
Labels: bug

#548 Add is_instance_valid check for highlighting item in snap-zone
  addons/godot-xr-tools/objects/snap_zone.gd
Labels: bug
